### ISSUE TITLE
rviz fails to build using wx-2.9 - AddPendingEvent is inaccessible  (ros-pkg ticket #5156)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#431]
When compiling rviz on OS X 10.7 using wx-2.9 rviz fails to compile with this:

{{{
/usr/local/lib/wxPython-2.9.2.1/include/wx-2.9/wx/event.h:3055: error: ‘virtual void wxEvtHandler::AddPendingEvent(const wxEvent&)’ is inaccessible
/Users/william/devel/ros/visualization/rviz/src/rviz/default_plugin/interactive_markers/interactive_marker.cpp:461: error: within this context
}}}

I have determined this is due to a change in the API from wx-2.8 to wx-2.9 which changes the accessibility of the AddPendingEvent function from outside the render window class.

I will be attaching a patch soon that checks for wx-2.9 and creates a pass through function to allow this to work in wx-2.9.

Tested on OS X 10.7 with wx-2.9.  This has not been tested on Linux with wx-2.8.

trac data:
- Owner: **hersh**
- Reporter: **wjwwood**
- Reported at: **Sat Sep 10 19:51:36 2011**
- URL: http://code.ros.org/trac/ros-pkg/ticket/5156
