### PR TITLE
Fix compatibility with Ogre 1.10, 1.11, 1.12

### PR DESCRIPTION
**Pull request by rhaschke**
This is a cleanup of #1242. Most work was already done by @de-vri-es, but some issues were remaining. The main API changes in Ogre are:
* The removal of `SimpleRenderable::setMaterial(const std::string & name)`.
* A _strict_ group handling in resource manager, which avoids searching resources in all available groups. Additionally, methods like `resourceExists(const std::string & name)` and `remove(const std::string & name)` expect the _correct_ group name now (but allow for a default).
To maintain compatibility with Ogre 1.9, which misses those group arguments, I had to push all resources into the default group.

Further, this PR:
* adds a cross-version compatibility function for setting materials on a `SimpleRenderable`
* loads the `freeimage` codec plugin, required to load images (and textures)
* avoids the use of relative paths in shader programs because they break in Ogre 1.11
* prevents removing anonymous scene nodes by name
* Uses OgrePrequisites.h to avoid conflict of class-forward vs. typedef for `Ogre::Vector3`
* recursively adds `ogre_media/fonts` as a resource location

As this is a huge PR with several potential side effects, it is only targeted for Noetic, but I successfully ran `marker_test`, `mesh_marker_test` and tested selection.

For compatibility with Ogre 1.9, we need to rely on now deprecated Ogre API (essentially Ogre's `SharedPtr` was replaced by `std::shared_ptr`), which is why I disabled corresponding warnings.
If a newer Ogre version is (hopefully) released into Ubuntu 20.04, this needs to be cleaned further.

### CODE REVIEW

**Comment by rhaschke** [comment]
When I will get positive feedback from @de-vri-es and @ProfFan, I will fast-forward noetic-devel.

**Comment by simonschmeisser** [comment]
I successfully build ogre 1.12.2 as an ubuntu deb package based on the 1.9.0 debian package and will test this branch with it in the next days and then try to get it into debian testing which would then lead to it being included in ubuntu 20.04 automagically. It's my first attempt at trying to contribute to ubuntu/debian so it will likely take some time. If my initial testing with this branch is successful I'll also create a PPA so you can test the packaging/branch as well.

**Comment by de-vri-es** [comment]
I'm not currently in the best position to test this. @hgaiser: Can you test it, or find someone else at Fizyr to test it?

**Comment by hgaiser** [comment]
I'll see if I can test this tomorrow.

**Comment by simonschmeisser** [comment]
I got the following error when trying to compile with my new ogre-1.12 package
```
In file included from panel_dock_widget.sip:7:0:
/home/simon/proggn/isys/ws/src/rviz/src/rviz/panel_dock_widget.h:34:10: fatal error: rviz/rviz_export.h: No such file or directory
 #include "rviz/rviz_export.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [siplibrviz_sipcmodule.o] Error 1
```
Did you see that before?

**Comment by rhaschke** [comment]
@simonschmeisser, this issue isn't particularly related to Ogre. Obviously this dynamically created header file, isn't in the include path for the sip python wrapper. I haven't seen this issue before.
Could you please check, whether and where this file is located - in build, devel, or install space?

File: src/python_bindings/sip/CMakeLists.txt [hunk 1]
```diff
@@ -54,6 +54,7 @@ endif()
 if(sip_helper_FOUND)
   list(APPEND rviz_BINDINGS "sip")
   set(rviz_BINDINGS "${rviz_BINDINGS}" PARENT_SCOPE)
+  get_property(rviz_sip_INCLUDE_DIRS DIRECTORY PROPERTY INCLUDE_DIRECTORIES)
```
Comment (simonschmeisser) [inline src/python_bindings/sip/CMakeLists.txt]:
```suggestion
  get_property(dir_includes DIRECTORY PROPERTY INCLUDE_DIRECTORIES)
  set(rviz_sip_INCLUDE_DIRS ${dir_includes} ${rviz_sip_INCLUDE_DIRS})
```

this combines both the manually crafted list from above as well as the one that is set for the directory (which probably adds the build directory where rviz_export.h is found)

**Comment by simonschmeisser** [comment]
Next error is this:
```
g++ -c -std=c++14 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -O2 -Wall -W -D_REENTRANT -DNDEBUG -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_GUI_LIB -I. -I/usr/lib/include -I/usr/include/eigen3 -I/usr/include/OGRE -I/usr/include/OGRE/Overlay -I/usr/include -I/usr/include/python2.7 -I/home/simon/proggn/isys/ws/src/rviz/src -I/opt/ros/melodic/include -I/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/home/simon/proggn/isys/ws/build/rviz/src/rviz -I/usr/share/qt5/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/X11R6/include -o siplibrviz_siprvizBoolProperty.o siplibrviz_siprvizBoolProperty.cpp
/home/simon/proggn/isys/ws/build/rviz/sip/rviz_sip/siplibrviz_siprvizBoolProperty.cpp:142:10: error: 'bool siprviz_BoolProperty::getReadOnly()' marked 'override', but does not override
     bool getReadOnly() SIP_OVERRIDE;
          ^~~~~~~~~~~
Makefile:18: recipe for target 'siplibrviz_siprvizBoolProperty.o' failed
```
which might be due to getReadOnly being const in the actual code but not in the sip definitions

**Comment by simonschmeisser** [comment]
success!
```
[ INFO] [1570695804.185048816]: rviz version 1.13.5
[ INFO] [1570695804.185090094]: compiled against Qt version 5.13.1
[ INFO] [1570695804.185101978]: compiled against OGRE version 1.12.2 (Rhagorthua)
[ INFO] [1570695804.193143098]: Forcing OpenGl version 0.
[ INFO] [1570695804.332504804]: Stereo is NOT SUPPORTED
[ INFO] [1570695804.332576435]: OpenGl version: 3 (GLSL 1.3).
[ERROR] [1570695804.355941864]: Error: ScriptCompiler - unexpected token in liberation_sans.fontdef(1): 'Liberation'. If this is a legacy script you must prepend the type (e.g. font, overlay).
```

**Comment by simonschmeisser** [comment]
the future looks dark :(
grafik
`
roslaunch fanuc_cr7ia_support test_cr7ia.launch
`
from here: https://github.com/ros-industrial/fanuc 

meshes are stl files

**Comment by hgaiser** [comment]
I followed the same path as @simonschmeisser , but used a different (private) package for the robot model. For me it did visualize the meshes properly.

Other than this I haven't tried much in rviz, but it seems to work from what I can tell, with the exception of the error which is also logged by @simonschmeisser but not mentioned:

```
[ERROR] [1570695804.355941864]: Error: ScriptCompiler - unexpected token in liberation_sans.fontdef(1): 'Liberation'. If this is a legacy script you must prepend the type (e.g. font, overlay).
```

**Comment by de-vri-es** [comment]
Note the font thing was fixed somewhere too. I think the font name simply needed quotes around it in the script. That may have been lost in the PR migration.

See this commit by @ProfFan:
https://github.com/fizyr-forks/rviz/pull/1/commits/48e6dd22e9dccd4ccf89cd7c7021bbbb2f64db73

**Comment by simonschmeisser** [comment]
> I followed the same path as @simonschmeisser , but used a different (private) package for the robot model. For me it did visualize the meshes properly.

I guess your model uses collada/DAE meshes instead of plain STL ones. Their material handling and therefore lighting is handled separately, we fixed that a couple of times recently so I guess @rhaschke knows where to look :)

**Comment by hgaiser** [comment]
> I guess your model uses collada/DAE meshes instead of plain STL ones. Their material handling and therefore lighting is handled separately, we fixed that a couple of times recently so I guess @rhaschke knows where to look :)

Indeed, it uses DAE :)

**Comment by rhaschke** [comment]
> > Error: ScriptCompiler - unexpected token in liberation_sans.fontdef(1): 'Liberation'. If this is a legacy script you must prepend the type (e.g. font, overlay).

> Note the font thing was fixed somewhere too. I think the font name simply needed quotes around it in the script. That may have been lost in the PR migration.

The key issue here is that the syntax of font definition files has changed: Newer versions require the "font" type to be mentioned, while older version cannot handle this.
To have the same rviz code working with old (1.9) and new Ogre versions, I added both, the old and the new syntax to the font definition file, which causes this warning message.

**Comment by hgaiser** [comment]
If it should be considered a warning, can it be changed to be printed as a warning?

**Comment by rhaschke** [comment]
@simonschmeisser, I cannot reproduce your issue https://github.com/ros-visualization/rviz/pull/1434#issuecomment-540460497 with Ogre 1.11.6. The rendering looks fine:
image

**Comment by rhaschke** [comment]
Same result for Ogre 1.12.2. I'm afraid, @simonschmeisser, you need to debug yourself.

**Comment by rhaschke** [comment]
I cleaned up the commit history.

**Comment by simonschmeisser** [comment]
Ah, it might be possible that this the good old locale issue again ... was doing the tests on my private notebook which might not have the fixes installed? Will check at some point during the weekend

**Comment by rhaschke** [comment]
That would be an explanation indeed. Awaiting your feedback.

**Comment by simonschmeisser** [comment]
Yes, sorry for the confusion, `LANG=c` did the trick and it now looks normal. :+1:

**Comment by rhaschke** [comment]
Hi @simonschmeisser,
in https://github.com/ros-visualization/rviz/pull/1434#issuecomment-538784504 you mentioned that you were working on a .deb package to get a newer Ogre version into Ubuntu 20.04 / ROS Noetic. Did you make progress with this?
The 20.04 pre-release I installed at the weekend didn't include a newer Ogre yet.

**Comment by simonschmeisser** [comment]
It's still WIP but it seems we're close I'm told. Basically there are still at least two warnings from the Debian linter that should be gone before uploading it to the Debian incoming queue. You can check out the current state at

https://salsa.debian.org/games-team/ogre/tree/ogre-1.12

**Comment by simonschmeisser** [comment]
@rhaschke I just tried to compile noetic-devel but it failed, your personal branch works, could you check what's happening?

ogre-1.12 has been sitting in the Debian NEW-queue for almost three weeks now, I hope it will be handled soon!

**Comment by rhaschke** [comment]
Looks like, I missed to forward the noetic branch. Sorry for that. I forwarded the branch and verified that it compiles. There are some open issues before a release though. For example, the initial size of the RenderWidget is not correctly recognized anymore.

**Comment by simonschmeisser** [comment]
Thanks, yes I noticed that as well. I had the impression that was on 1.12 only and not on 1.9? Will recheck.

**Comment by simonschmeisser** [comment]
finally ... https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=ogre-1.12
